FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    libpng-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    zip


RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath


COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer


WORKDIR /var/www


COPY . .


RUN [ ! -f .env ] && cp .env.example .env || true


RUN composer install --no-dev --optimize-autoloader --no-interaction


RUN php artisan key:generate --force


RUN chmod -R 775 storage bootstrap/cache


RUN php artisan config:clear \
    && php artisan route:clear \
    && php artisan view:clear


EXPOSE 10000

CMD php artisan serve --host=0.0.0.0 --port=10000
